### ISSUE TITLE
Unable to get package to work

### ISSUE THREAD

**Issue by csalvato** [ryanwilsonperkin/buildkite-dl#1]
I am seeing some issue that I don't know how to resolve.

First, when I don't have `Read Artifacts` checked, I see this message:

![image](https://user-images.githubusercontent.com/1158152/175967641-1b188ec2-8401-448b-8485-8207973832d8.png)

When I have `Read Artifacts` checked, I see no output:

<img width="811" alt="Screen Shot 2022-06-27 at 08 42 39" src="https://user-images.githubusercontent.com/1158152/175968134-6a7b6613-42a7-4a46-832d-91d5157b168c.png">

Here's a screenshot of the Token config:

![image](https://user-images.githubusercontent.com/1158152/175967956-f2ead312-816a-4e53-9f1d-300bef87e587.png)

**Comment by ryanwilsonperkin** [comment]
Token permissions look correct (only "Read Builds" and "Read Artifacts" are required, but it looks like the build at that URL didn't produce any `junit.xml` test artifacts. I should update the docs to reflect that that's required, and potentially update the tool to give some appropriate warning messages if it can't find any.
